apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: wf-market-gsheet
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: wf-market-gsheet
              image: gcr.io/medrover/wf-market-gsheet:0.52
              env:
                - name: GOOGLE_SHEETS_SERVICE_ACCOUNT
                  value: "/mnt/gs_key/service_account.json"
              resources:
                requests:
                  cpu: 0.25
                  memory: 206Mi
                limits:
                  cpu: 0.5
                  memory: 1.5Gi
              volumeMounts:
                - name: wf-market-gsheet-service-account-volume
                  mountPath: "/mnt/gs_key/"
                  readOnly: true
          volumes:
            - name: wf-market-gsheet-service-account-volume
              secret:
                secretName: wf-market-gsheet-service-account
          restartPolicy: Never
      backoffLimit: 0
